# application.yaml
spring:
  application:
    name: event-ingestion-service

server:
  error:
    include-stacktrace: never

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics